storage:
  type: sqlite
  mysql:
    host: "localhost"
    port: 3306
    database: pit
    username: root
    password: 123456
    property: useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&autoReconnect=true
worlds:
  active_arena: "world"
  world_manager:
    world:
      monster_spawns: []
      time_lock:
        enabled: true
        time: 6000
      weather:
        change: false
        storm: false
        thundering: false
        player_weather: CLEAR
      max_build_height: 100.0
      spawn_location:
        x: 9.5
        y: 114
        z: 0.5
        pitch: 0.0
        yaw: -90.0
      spawn_pos1:
        x: -20
        y: 100
        z: -20
      spawn_pos2:
        x: 20
        y: 200
        z: 20
settings:
  bossbar:
    title_format: "&6%name% &7- &c%health% &7/ &c%max_health%"
  level:
    level_format:
      0: "&7[%level%✫]"
      100: "&f[%level%✫]"
      200: "&6[%level%✫]"
      300: "&b[%level%✫]"
      400: "&a[%level%✫]"
      500: "&c[%level%✫]"
      600: "&e[%level%✫]"
      700: "&d[%level%✫]"
      800: "&3[%level%✫]"
      900: "&2[%level%✫]"
      1000: "&a[&c%level_1%&e%level_2%&a%level_3%&b%level_4%&d✪&a]"
      2000: "&b[%level_1%&3%level_2%%level_3%&b%level_4%❄]"
      3000: "&d[%level_1%&5%level_2%%level_3%&d%level_4%✿]"
      4000: "&a[%level_1%&2%level_2%%level_3%&a%level_4%✤]"
      5000: "&e[%level_1%&6%level_2%%level_3%&e%level_4%⚝]"
      10000: "&6[&e%level%⚝&6]"
  tablist:
    enable: true
    header:
      - "&e&lTHE PIT"
      - ""
      - "&7You are playing the pit"
      - "&7Kills: &f%kills%  &7Deaths: &f%deaths%  &7Killstreak: &f%killstreak%"
      - ""
    footer:
      - ""
      - "&6www.easycraft.com"
  scoreboard:
    enable: true
    title: "&6&lTHE PIT"
    status:
      fight: "&cFighting"
      wait: "&aWaiting"
      develop_mode: "&6Developing"
    lines:
      - "&8%date%"
      - ""
      - "&fLevel: &7%pit_level_without_brackets%"
      - ""
      - "&fProgress: &7%pit_exp% / 5k"
      - " %pit_expbar%"
      - ""
      - "&fGold: &r&7%xconomy_balance%"
      - "&fStatus: &7%status%"
      - ""
      - "&fVersion: &71.0"
      - ""
      - "&ewww.easycraft.com"
  fighting:
    duration: 50
  gain_gold:
    enable: true
    gold_spawn:
      spawn_location:
        x: 0
        y: 82
        z: 0
      radius: 100
    amount:
      max: 10
      min: 5
  murder:
    gain_exp:
      enable: true
      amount:
        max: 500
        min: 300
    gain_gold:
      enable: true
      amount:
        max: 100
        min: 50
title:
  death:
    title: "&c&lYOU DIED!"
    subtitle: "&7You will be teleported to spawn point."
  develop_mode:
    action_bar: "&a&lDEVELOP MODE ENABLED"
  level_up:
    title: "&c&l%level% &r-> &a&l%new_level%"
    subtitle: "&7You have leveled up!"
  murder:
    action_bar: "&7You killed %dead%!  &6+%gold%  &b+%exp%"
